#%RAML 1.0
title: First_api
/first:
  get:
    description: this my first api
    responses:
      200:
        body:
          application/json:
            example:
              {
                "id":123
              }
          

      

    